# Generated by Django 5.1.1 on 2024-10-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imageprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiModel',
        ),
    ]
